#!/bin/sh -e

CMD=$(basename "$0")

JAVA_HOME=$(/usr/libexec/java_home -v 10 2>/dev/null)
VMOPTS="--add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/sun.net.dns=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/sun.security.x509=ALL-UNNAMED"

./gradlew -q installDist

BCP=
DEBUG=
#DEBUG=-agentlib:jdwp=transport=dt_socket,server=y,address=localhost:5005,suspend=y
#DEBUG="-Djavax.net.debug=ssl:handshake -Djava.security.debug=sunpkcs11"

JAVA_CMD="$JAVA_HOME/bin/java"

MAIN_JAR=$(ls build/install/oksocial/lib/oksocial-*.jar | grep -v oksocial-output)
${JAVA_HOME}/bin/java ${DEBUG} ${VMOPTS} -classpath ${MAIN_JAR}:build/install/oksocial/lib/\* -Dcommand.name="$CMD" com.baulsupp.oksocial.kotlin.Main "$@"
