#!/bin/sh -e

CMD=$(basename "$0")

export JAVA_HOME=$(/usr/libexec/java_home -v 1.8 2>/dev/null)
export INSTALLDIR=.

./gradlew -q installDist

BCP=
#DEBUG=-agentlib:jdwp=transport=dt_socket,server=y,address=localhost:5005,suspend=y
#DEBUG="-Djavax.net.debug=ssl:handshake -Djava.security.debug=sunpkcs11"

JAVA_HOME=$(/usr/libexec/java_home -v 1.8 2>/dev/null)

JAVA_CMD="$JAVA_HOME/bin/java"

MAIN_JAR=$(ls build/install/oksocial/lib/oksocial-*.jar | grep -v oksocial-output)
$JAVA_HOME/bin/java -Dio.netty.processId=$$ $VMOPTS $DEBUG -classpath $MAIN_JAR:build/install/oksocial/lib/\* -Dcommand.name="$CMD" com.baulsupp.oksocial.kotlin.Main "$@"
