#!/bin/sh -e

CMD=$(basename "$0")

VMOPTS="--add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/sun.net.dns=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/sun.security.x509=ALL-UNNAMED"

./gradlew -q installDist

BCP=
DEBUG=

MAIN_JAR=$(ls build/install/okurl/lib/okurl-*.jar | grep -v okurl-output)
java ${DEBUG} ${VMOPTS} -classpath ${MAIN_JAR}:build/install/okurl/lib/\* -Dcommand.name="$CMD" com.baulsupp.okurl.kotlin.MainKt "$@"
