#!/bin/sh

set -e

codesha() {
  find pom.xml src -type f | sort | xargs shasum | shasum | cut -f 1 -d ' '
}

SHA=$(codesha)

if [ ! -f "target/cached-$SHA.jar" ]; then
  mvn -DskipTests clean package dependency:copy-dependencies
  mv target/oksocial-*SNAPSHOT.jar "target/cached-$SHA.jar"
fi

JAVA_CMD=java
BCP=
#DEBUG=-agentlib:jdwp=transport=dt_socket,server=y,address=localhost:5005,suspend=y
DEBUG=-Djavax.net.debug=ssl:handshake

if [ -x /usr/libexec/java_home ]; then
  JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

  if [ $? -eq 0 ]; then
    JAVA_CMD="$JAVA_HOME/bin/java"
    ALPN=$(ls target/alpn/alpn-boot-*.jar)
    BCP="-Xbootclasspath/p:$ALPN"
  fi
fi

MAIN_JAR=$(ls "target/cached-$SHA.jar")
$JAVA_CMD $DEBUG $BCP -classpath $MAIN_JAR:target/dependency/\* com.baulsupp.oksocial.Main "$@"

