#!/bin/sh -e

CMD=$(basename "$0")

export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export INSTALLDIR=.

./gradlew -q installDist

BCP=
#DEBUG=-agentlib:jdwp=transport=dt_socket,server=y,address=localhost:5005,suspend=y
#DEBUG="-Djavax.net.debug=ssl:handshake -Djava.security.debug=sunpkcs11"

JAVA_HOME=$(/usr/libexec/java_home -v 9 2>/dev/null)

if [ $? -ne 0 ]; then
  JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

  if [ $? -eq 0 ]; then
    ALPN=$(ls target/alpn/alpn-boot-*.jar)
    BCP="-Xbootclasspath/p:$ALPN"
  fi
else
  VMOPTS="--add-opens=java.base/sun.net.dns=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED  --add-opens=java.base/java.nio=ALL-UNNAMED  --add-opens=java.base/sun.nio.ch=ALL-UNNAMED"
fi

JAVA_CMD="$JAVA_HOME/bin/java"

MAIN_JAR=$(ls build/install/oksocial/lib/oksocial-*.jar | grep -v oksocial-output)
$JAVA_HOME/bin/java -Dio.netty.processId=$$ $VMOPTS $DEBUG $BCP -classpath $MAIN_JAR:build/install/oksocial/lib/\* -Dcommand.name="$CMD" com.baulsupp.oksocial.Main "$@"
