#!/bin/sh

CMD=$(basename "$0")

export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export INSTALLDIR=.

codesha() {
  find pom.xml src/main -type f | sort | xargs shasum | shasum | cut -f 1 -d ' '
}

SHA=$(codesha)

if [ ! -f "target/cached-$SHA.jar" ]; then
  echo Building... >&1
  mvn -B -q -DskipTests clean package dependency:copy-dependencies >&2 || exit
  mv target/oksocial-*SNAPSHOT.jar "target/cached-$SHA.jar"
fi

#DEBUG=-agentlib:jdwp=transport=dt_socket,server=y,address=localhost:5005,suspend=y
DEBUG="-Djavax.net.debug=ssl:handshake"

JAVA_CMD="$JAVA_HOME/bin/java"

MAIN_JAR=$(ls "target/cached-$SHA.jar")
$JAVA_HOME/bin/java -Dokhttp.platform=conscrypt $VMOPTS $DEBUG -classpath $MAIN_JAR:target/dependency/\* -Dcommand.name="$CMD" com.baulsupp.oksocial.Main "$@"
