#!/bin/sh

export INSTALLDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
PLUGINDIR=/dev/null

if [ -x /usr/libexec/java_home ]; then
  JAVA_HOME=$(/usr/libexec/java_home -v 9 2>/dev/null)

  if [ $? -ne 0 ]; then
    JAVA_HOME=$(/usr/libexec/java_home -v 1.8 2>/dev/null)
    ALPN=$(ls $INSTALLDIR/lib/alpn-boot-*.jar)
    BCP="-J-Xbootclasspath/p:$ALPN"
  else
    VMOPTS="-J--add-opens=java.base/sun.net.dns=ALL-UNNAMED -J--add-opens=java.base/java.lang.reflect=ALL-UNNAMED  -J--add-opens=java.base/java.nio=ALL-UNNAMED  -J--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"
  fi
fi

CLASSPATH=$(JARS=($INSTALLDIR/lib/*.jar); IFS=:; echo "${JARS[*]}")

PLUGINS=

for i in `find $PLUGINDIR -name lib 2>/dev/null`; do
  PLUGINS=$PLUGINS:$i/\*
done

if [ -z "$1" ]; then
  input=-
else
  input=$1
  shift
fi

$JAVA_HOME/bin/jjs $VMOPTS $BCP -classpath "$CLASSPATH$PLUGINS" -scripting $INSTALLDIR/scripts/oksocial.js $input -- "$@"
