#!/bin/sh

INSTALLDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

if [ -x /usr/libexec/java_home ]; then
  JAVA_HOME=$(/usr/libexec/java_home -v 9 2>/dev/null)

  if [ $? -ne 0 ]; then
    JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
    ALPN=$(ls target/alpn/alpn-boot-*.jar)
    BCP="-Xbootclasspath/p:$ALPN"
  fi
fi

$JAVA_HOME/bin/jjs $BCP -classpath $(ls $INSTALLDIR/lib/*.jar | tr '\n' ':') -scripting "$@"
