#!/bin/sh

JAVA_CMD=java
INSTALLDIR=.

if [ -x /usr/libexec/java_home ]; then
  JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

  if [ $? -eq 0 ]; then
    JAVA_CMD="$JAVA_HOME/bin/java"
    BCP="-Xbootclasspath/p:$INSTALLDIR/alpn/alpn-boot-8.1.2.v20141202.jar"
  fi
fi

$JAVA_CMD $BCP -classpath $INSTALLDIR/lib/\* com.baulsupp.oksocial.Main "$@"
