#!/bin/sh

CMD=$(basename $0)

export INSTALLDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

JAVA_CMD=java
if [ -x /usr/libexec/java_home ]; then
  JAVA_HOME=$(/usr/libexec/java_home -v 9 2>/dev/null)
  
  if [ $? -ne 0 ]; then
    JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

    ALPN=$(ls $INSTALLDIR/alpn/alpn-boot-*.jar)
    BCP="-Xbootclasspath/p:$ALPN"
  fi
  
  JAVA_CMD=$JAVA_HOME/bin/java
fi

$JAVA_CMD $BCP -classpath $INSTALLDIR/lib/\* -Dcommand.name=$CMD com.baulsupp.oksocial.Main "$@"
