#!/bin/sh

CMD=$(basename $0)

export INSTALLDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

JAVA_CMD=java
if [ -x /usr/libexec/java_home ]; then
  VMOPTS="--add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/sun.net.dns=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/sun.security.x509=ALL-UNNAMED"

  JAVA_HOME=$(/usr/libexec/java_home -v 11 2>/dev/null)

  if [ $? -ne 0 ]; then
    JAVA_HOME=$(/usr/libexec/java_home -v 10 2>/dev/null)

    if [ $? -ne 0 ]; then
      JAVA_HOME=$(/usr/libexec/java_home -v 9 2>/dev/null)

      if [ $? -ne 0 ]; then
        JAVA_HOME=$(/usr/libexec/java_home -v 1.8 2>/dev/null)
        VMOPTS=""
      fi
    fi
  fi

  JAVA_CMD=${JAVA_HOME}/bin/java
fi

${JAVA_CMD} ${VMOPTS} -classpath ${INSTALLDIR}/lib/\* -Dcommand.name=${CMD} com.baulsupp.okurl.Main "$@"
