name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build
        run: ./gradlew check

      - name: Show Reports
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: reports-${{ runner.os }}
          path: build/
